### ISSUE TITLE
Поиск по вопросам не работает - показываются результаты не соответствующие строке поиска

### ISSUE THREAD

**Issue by SvetlanaKantola** [SvetlanaKantola/TestOtvetMailRu#3]
Как воспроизвести":
1)открываем страницу otvet.mail.ru 
2)выбираем категорию "Образование"
3)в поле "Поиск по вопросам" вводим слово "диктант"
4)Нажмите кнопку "Найти" в виде лупы или просто ввод 

"Фактический результат": идет переход по ссылке https:://otvet.mail.ru/education/диктант
появляются множество вопросов не имеющих к искомому отношения см. attach

"Ожидаемый результат":  переход должен привести к выборке вопросов в категории образование со словом "диктант" в контексте
[dz2_bug3.docx](https://github.com/SvetlanaKantola/TestOtvetMailRu/files/32928/dz2_bug3.docx)

**Comment by yevsikov** [comment]
В тест-плане вы перепутали понятия <a href="http://www.protesting.ru/testing/types/loadtesttypes.html">"стресс-тестирование"</a> (<a href="http://universarium.org/course/445/module/5/lecture/4">Модуль 5, лекция 4</a>) и "<a href="http://www.softwaretestinghelp.com/what-is-negative-testing/">негативное тестирование</a>"

**Comment by vk0** [comment]
Не воспроизводится, переходит по ссылке  https://otvet.mail.ru/search/%D0%B4%D0%B8%D0%BA%D1%82%D0%B0%D0%BD%D1%82

**Comment by SvetlanaKantola** [comment]
Да, ссылка при поиске поправлена
